// @ts-check
import { defineConfig } from 'astro/config';
import react from '@astrojs/react';
import vercel from '@astrojs/vercel';

export default defineConfig({
  site: 'https://alloygp.co',
  output: 'server',
  adapter: vercel(),
  trailingSlash: 'never',
  integrations: [react()],
  prefetch: { prefetchAll: true },
  security: { checkOrigin: false },
  build: {
    inlineStylesheets: 'auto',
  },
  redirects: {
    '/index.html': '/',
    '/about.html': '/about',
    '/about/testimonials.html': '/about/testimonials',
    '/we-know-cam.html': '/we-know-cam',
    '/contact.html': '/contact',
    '/strategic-review-request.html': '/strategic-review-request',
    '/services.html': '/services',
    '/hoa-cam-marketing-services.html': '/hoa-cam-marketing-services',
    '/services/newsletter-production-for-hoa-management': '/services/hoa-newsletter-production',
    '/services/newsletter-production-for-hoa-management/': '/services/hoa-newsletter-production',
    '/property-management-seo.html': '/property-management-seo',
    '/hoa-board-education-programs.html': '/hoa-board-education-programs',
    '/groundwork.html': '/groundwork',
    '/boardsuite.html': '/boardsuite',
    '/our-approach.html': '/our-approach',
    '/our-approach/boardreach.html': '/our-approach/boardreach',
    '/our-approach/boardmatch.html': '/our-approach/boardmatch',
    '/our-approach/boardretain.html': '/our-approach/boardretain',
    '/resource-hub.html': '/resource-hub',
    '/resource-hub/ai-search-for-cam.html': '/resource-hub/ai-search-for-cam',
    '/resource-hub/cam-marketing-strategy.html': '/resource-hub/cam-marketing-strategy',
    '/courses.html': '/courses',
    // Legacy lesson route → new lesson system
    '/courses/trust-building-lesson': '/courses/trust-building/lessons/intro',
    // Old WordPress course URLs → new clean URLs
    '/courses/trust-building-for-cam-firms-reviews-testimonials-case-studies': '/courses/trust-building',
    '/courses/trust-building-for-cam-firms-reviews-testimonials-case-studies/lessons/intro-to-trust-building-for-cam-firms-reviews-testimonials-case-studies': '/courses/trust-building/lessons/intro',
    '/courses/trust-building-for-cam-firms-reviews-testimonials-case-studies/lessons/why-trust-signals-matter-to-hoa-boards': '/courses/trust-building/lessons/why-trust-signals-matter',
    '/courses/trust-building-for-cam-firms-reviews-testimonials-case-studies/lessons/what-reviews-are-and-why-they-carry-weight': '/courses/trust-building/lessons/what-reviews-are',
    '/courses/trust-building-for-cam-firms-reviews-testimonials-case-studies/lessons/reviews-extra-factors-that-influence-impact': '/courses/trust-building/lessons/reviews-extra-factors',
    '/courses/trust-building-for-cam-firms-reviews-testimonials-case-studies/lessons/what-testimonials-are-and-why-they-stand-out': '/courses/trust-building/lessons/what-testimonials-are',
    '/courses/trust-building-for-cam-firms-reviews-testimonials-case-studies/lessons/testimonials-extra-factors-that-influence-impact': '/courses/trust-building/lessons/testimonials-extra-factors',
    '/courses/trust-building-for-cam-firms-reviews-testimonials-case-studies/lessons/what-case-studies-are-and-why-they-convince': '/courses/trust-building/lessons/what-case-studies-are',
    '/courses/trust-building-for-cam-firms-reviews-testimonials-case-studies/lessons/case-studies-extra-factors-that-influence-impact': '/courses/trust-building/lessons/case-studies-extra-factors',
    '/courses/trust-building-for-cam-firms-reviews-testimonials-case-studies/lessons/recapping-the-3-trust-signals': '/courses/trust-building/lessons/recapping-trust-signals',
    '/courses/trust-building-for-cam-firms-reviews-testimonials-case-studies/lessons/from-proof-to-persuasion-using-trust-signals-effectively': '/courses/trust-building/lessons/from-proof-to-persuasion',
    '/courses/trust-building-for-cam-firms-reviews-testimonials-case-studies/quizzes/check-your-learning-trust-building-for-cam-firms-reviews-testimonials-case-studies': '/courses/trust-building-quiz',
    '/results.html': '/results',
    '/results/rise-amg.html': '/results/apex-cmg',
    '/results/rise-amg': '/results/apex-cmg',
    '/faq.html': '/faq',
    '/terms-conditions.html': '/terms-conditions',
    '/privacy-policy.html': '/privacy-policy',
  },
});
